"""Render docs/mcp/tools_catalog.md from the live MCP server so the catalog can't drift.

Regenerate with: python -m softone_mcp.catalog
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from softone_mcp.server import mcp

CATALOG_PATH = Path(__file__).resolve().parent.parent / "docs" / "mcp" / "tools_catalog.md"

HEADER = """# MCP tools catalog

<!-- Generated by `python -m softone_mcp.catalog`. Do not edit by hand. -->

Every tool returns the same envelope:

- Success: `{"ok": true, "data": ..., "meta": {"trace_id", "tool", "actions"}}`
- Error: `{"ok": false, "error": {"code", "message", "details"}, "meta": {...}}`

Call `softone_connect_default` first and pass its `session_id` to every other tool.
"""


def _type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " or ".join(_type(s) for s in schema["anyOf"])  # not "|": it would split the table cell
    if schema.get("type") == "array":
        return f"list[{_type(schema.get('items', {}))}]"
    return schema.get("type", "any")


def render() -> str:
    tools = asyncio.run(mcp.list_tools())
    out = [HEADER, f"## Tools ({len(tools)})\n", "| Tool | What it does |", "|---|---|"]
    out += [f"| [`{t.name}`](#{t.name}) | {(t.description or '').split('. ')[0].rstrip('.')} |" for t in tools]
    for t in tools:
        out += ["", f"### `{t.name}`", "", t.description or ""]
        props = t.inputSchema.get("properties", {})
        required = set(t.inputSchema.get("required", []))
        if props:
            out += ["", "| Param | Type | Required | Description |", "|---|---|---|---|"]
            out += [
                f"| `{name}` | `{_type(p)}` | {'yes' if name in required else ''} | {p.get('description', '')} |"
                for name, p in props.items()
            ]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    CATALOG_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {CATALOG_PATH}")
